Q1. What is the total revenue generated by male vs. female customers?

SELECT gender,
       SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY gender;

------------------------------------------------------------

Q2. Which gender spends more on average purchases?

SELECT gender,
       ROUND(AVG(purchase_amount),2) AS avg_purchase
FROM customer
GROUP BY gender
ORDER BY avg_purchase DESC;

------------------------------------------------------------

Q3. Which are the top 10 products with the highest average review rating?

SELECT item_purchased,
       ROUND(AVG(review_rating),2) AS avg_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 10;

------------------------------------------------------------

Q4. Compare the average purchase amounts between different shipping methods.

SELECT shipping_type,
       ROUND(AVG(purchase_amount),2) AS avg_purchase
FROM customer
GROUP BY shipping_type
ORDER BY avg_purchase DESC;

------------------------------------------------------------

Q5. Do subscribed customers spend more? And Compare customer count, average spend, and total revenue.

SELECT subscription_status,
       COUNT(*) AS customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY subscription_status;

------------------------------------------------------------

Q6. What percentage of purchases had discounts applied?

SELECT discount_applied,
       COUNT(*) AS purchase_count,
       ROUND(
           COUNT(*) * 100.0 /
           (SELECT COUNT(*) FROM customer),
           2
       ) AS percentage
FROM customer
GROUP BY discount_applied;

------------------------------------------------------------

Q7. Segment customers into New, Returning, and Loyal customers.

SELECT
CASE
    WHEN previous_purchases <= 10 THEN 'New'
    WHEN previous_purchases <= 30 THEN 'Returning'
    ELSE 'Loyal'
END AS customer_segment,
COUNT(*) AS customer_count
FROM customer
GROUP BY customer_segment;

------------------------------------------------------------

Q8. What are the top 3 most purchased products within each category?

WITH ranked_products AS (
    SELECT
        category,
        item_purchased,
        COUNT(*) AS purchase_count,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(*) DESC
        ) AS rn
    FROM customer
    GROUP BY category, item_purchased
)

SELECT *
FROM ranked_products
WHERE rn <= 3;

------------------------------------------------------------

Q9. Are repeat buyers more likely to subscribe?

SELECT
CASE
    WHEN previous_purchases > 5 THEN 'Repeat Buyer'
    ELSE 'Non Repeat Buyer'
END AS buyer_type,
subscription_status,
COUNT(*) AS customer_count
FROM customer
GROUP BY buyer_type, subscription_status;

------------------------------------------------------------

Q10. What is the revenue contribution of each age group?

SELECT age_group,
       SUM(purchase_amount) AS revenue
FROM customer
GROUP BY age_group
ORDER BY revenue DESC;